Repository esucsowt/website, pull requests merged in 2021-02, with the labels that each got.

#1 purposed fix to console cursor glitch
  .gitignore
  assets/css/master.css
  assets/js/console_text.js
  index.html
Labels: bug

#31 Accounts App
  website_project/accounts/__init__.py
  website_project/accounts/admin.py
  website_project/accounts/apps.py
  website_project/accounts/forms.py
  website_project/accounts/migrations/0001_initial.py
  website_project/accounts/migrations/__init__.py
  website_project/accounts/models.py
  website_project/accounts/templates/accounts/login.html
  website_project/accounts/templates/accounts/signup.html
  website_project/accounts/tests.py
  website_project/accounts/urls.py
  website_project/accounts/views.py
  website_project/django_app/apps.py
  website_project/django_app/models.py
  website_project/django_app/views.py
  website_project/django_project/settings.py.orig
  website_project/django_project/urls.py
  website_project/django_project/views.py
  website_project/static/css/master.css
  website_project/static/images/CSO_logo-02-02.png
  website_project/templates/base.html
  website_project/templates/test.html
  website_project/templates/thanks.html
Labels: css, html, new feature, python

#40 LoginView Adjustment
  website_project/accounts/forms.py
  website_project/accounts/views.py
Labels: bug, enhancement, python
